server:
  port: 8000
eureka:
  instance:
    hostname: 59.110.243.97
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

