server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://59.110.243.97:8000/eureka/

  # swagger-ui界面
  instance:
    status-page-url: http://59.110.243.97:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

# spring程序的名称
spring:
  application:
    name: syp-user

  #redis配置
  #Redis服务器地址
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
        #连接超时时间（毫秒）
        timeout: 5000

  # mysql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.243.97:3306/syp_station?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Syp123
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.syp.sypuser.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#showSql
logging:
  level:
    cn:
      syp:
        sypuser:
          mapper : info

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

